/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import * as z from "zod";

export type GetAgentsRequest = {
    /**
     * What entry offset to request
     */
    page?: number | undefined;
    /**
     * How many entries to return per page
     */
    limit?: number | undefined;
};

/**
 * Successfully fetched agents details.
 */
export type GetAgentsResponseBody = {
    data: Array<components.AgentJson>;
    /**
     * Meta details for pagination.
     */
    meta: components.MetaJson;
};

export type GetAgentsResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Successfully fetched agents details.
     */
    object?: GetAgentsResponseBody | undefined;
};

/** @internal */
export namespace GetAgentsRequest$ {
    export type Inbound = {
        page?: number | undefined;
        limit?: number | undefined;
    };

    export const inboundSchema: z.ZodType<GetAgentsRequest, z.ZodTypeDef, Inbound> = z
        .object({
            page: z.number().int().default(1),
            limit: z.number().int().default(10),
        })
        .transform((v) => {
            return {
                page: v.page,
                limit: v.limit,
            };
        });

    export type Outbound = {
        page: number;
        limit: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetAgentsRequest> = z
        .object({
            page: z.number().int().default(1),
            limit: z.number().int().default(10),
        })
        .transform((v) => {
            return {
                page: v.page,
                limit: v.limit,
            };
        });
}

/** @internal */
export namespace GetAgentsResponseBody$ {
    export type Inbound = {
        data: Array<components.AgentJson$.Inbound>;
        meta: components.MetaJson$.Inbound;
    };

    export const inboundSchema: z.ZodType<GetAgentsResponseBody, z.ZodTypeDef, Inbound> = z
        .object({
            data: z.array(components.AgentJson$.inboundSchema),
            meta: components.MetaJson$.inboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
                meta: v.meta,
            };
        });

    export type Outbound = {
        data: Array<components.AgentJson$.Outbound>;
        meta: components.MetaJson$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetAgentsResponseBody> = z
        .object({
            data: z.array(components.AgentJson$.outboundSchema),
            meta: components.MetaJson$.outboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
                meta: v.meta,
            };
        });
}

/** @internal */
export namespace GetAgentsResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        object?: GetAgentsResponseBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetAgentsResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            object: z.lazy(() => GetAgentsResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        object?: GetAgentsResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetAgentsResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            object: z.lazy(() => GetAgentsResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
