/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import * as z from "zod";

export type GetFactionsRequest = {
    /**
     * What entry offset to request
     */
    page?: number | undefined;
    /**
     * How many entries to return per page
     */
    limit?: number | undefined;
};

/**
 * Succesfully fetched factions.
 */
export type GetFactionsResponseBody = {
    data: Array<components.FactionJson>;
    /**
     * Meta details for pagination.
     */
    meta: components.MetaJson;
};

export type GetFactionsResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Succesfully fetched factions.
     */
    object?: GetFactionsResponseBody | undefined;
};

/** @internal */
export namespace GetFactionsRequest$ {
    export type Inbound = {
        page?: number | undefined;
        limit?: number | undefined;
    };

    export const inboundSchema: z.ZodType<GetFactionsRequest, z.ZodTypeDef, Inbound> = z
        .object({
            page: z.number().int().default(1),
            limit: z.number().int().default(10),
        })
        .transform((v) => {
            return {
                page: v.page,
                limit: v.limit,
            };
        });

    export type Outbound = {
        page: number;
        limit: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetFactionsRequest> = z
        .object({
            page: z.number().int().default(1),
            limit: z.number().int().default(10),
        })
        .transform((v) => {
            return {
                page: v.page,
                limit: v.limit,
            };
        });
}

/** @internal */
export namespace GetFactionsResponseBody$ {
    export type Inbound = {
        data: Array<components.FactionJson$.Inbound>;
        meta: components.MetaJson$.Inbound;
    };

    export const inboundSchema: z.ZodType<GetFactionsResponseBody, z.ZodTypeDef, Inbound> = z
        .object({
            data: z.array(components.FactionJson$.inboundSchema),
            meta: components.MetaJson$.inboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
                meta: v.meta,
            };
        });

    export type Outbound = {
        data: Array<components.FactionJson$.Outbound>;
        meta: components.MetaJson$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetFactionsResponseBody> = z
        .object({
            data: z.array(components.FactionJson$.outboundSchema),
            meta: components.MetaJson$.outboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
                meta: v.meta,
            };
        });
}

/** @internal */
export namespace GetFactionsResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        object?: GetFactionsResponseBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetFactionsResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            object: z.lazy(() => GetFactionsResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        object?: GetFactionsResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetFactionsResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            object: z.lazy(() => GetFactionsResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
