/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import * as z from "zod";

export type GetMyShipCargoSecurity = {
    agentToken: string;
};

export type GetMyShipCargoRequest = {
    /**
     * The symbol of the ship.
     */
    shipSymbol: string;
};

/**
 * Successfully fetched ship's cargo.
 */
export type GetMyShipCargoResponseBody = {
    /**
     * Ship cargo details.
     */
    data: components.ShipCargoJson;
};

export type GetMyShipCargoResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Successfully fetched ship's cargo.
     */
    object?: GetMyShipCargoResponseBody | undefined;
};

/** @internal */
export namespace GetMyShipCargoSecurity$ {
    export type Inbound = {
        AgentToken: string;
    };

    export const inboundSchema: z.ZodType<GetMyShipCargoSecurity, z.ZodTypeDef, Inbound> = z
        .object({
            AgentToken: z.string(),
        })
        .transform((v) => {
            return {
                agentToken: v.AgentToken,
            };
        });

    export type Outbound = {
        AgentToken: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetMyShipCargoSecurity> = z
        .object({
            agentToken: z.string(),
        })
        .transform((v) => {
            return {
                AgentToken: v.agentToken,
            };
        });
}

/** @internal */
export namespace GetMyShipCargoRequest$ {
    export type Inbound = {
        shipSymbol: string;
    };

    export const inboundSchema: z.ZodType<GetMyShipCargoRequest, z.ZodTypeDef, Inbound> = z
        .object({
            shipSymbol: z.string(),
        })
        .transform((v) => {
            return {
                shipSymbol: v.shipSymbol,
            };
        });

    export type Outbound = {
        shipSymbol: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetMyShipCargoRequest> = z
        .object({
            shipSymbol: z.string(),
        })
        .transform((v) => {
            return {
                shipSymbol: v.shipSymbol,
            };
        });
}

/** @internal */
export namespace GetMyShipCargoResponseBody$ {
    export type Inbound = {
        data: components.ShipCargoJson$.Inbound;
    };

    export const inboundSchema: z.ZodType<GetMyShipCargoResponseBody, z.ZodTypeDef, Inbound> = z
        .object({
            data: components.ShipCargoJson$.inboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
            };
        });

    export type Outbound = {
        data: components.ShipCargoJson$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetMyShipCargoResponseBody> = z
        .object({
            data: components.ShipCargoJson$.outboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
            };
        });
}

/** @internal */
export namespace GetMyShipCargoResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        object?: GetMyShipCargoResponseBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetMyShipCargoResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            object: z.lazy(() => GetMyShipCargoResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        object?: GetMyShipCargoResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetMyShipCargoResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            object: z.lazy(() => GetMyShipCargoResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
