/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import * as z from "zod";

export type PurchaseCargoSecurity = {
    agentToken: string;
};

export type PurchaseCargoPurchaseCargoRequest = {
    /**
     * The good's symbol.
     */
    symbol: components.TradeSymbolJson;
    /**
     * Amounts of units to purchase.
     */
    units: number;
};

export type PurchaseCargoRequest = {
    /**
     * The ship's symbol.
     */
    shipSymbol: string;
    requestBody?: PurchaseCargoPurchaseCargoRequest | undefined;
};

export type PurchaseCargoData = {
    /**
     * Agent details.
     */
    agent: components.AgentJson;
    /**
     * Ship cargo details.
     */
    cargo: components.ShipCargoJson;
    /**
     * Result of a transaction with a market.
     */
    transaction: components.MarketTransactionJson;
};

/**
 * Purchased goods successfully.
 */
export type PurchaseCargoPurchaseCargo201Response = {
    data: PurchaseCargoData;
};

export type PurchaseCargoResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Purchased goods successfully.
     */
    purchaseCargo201Response?: PurchaseCargoPurchaseCargo201Response | undefined;
};

/** @internal */
export namespace PurchaseCargoSecurity$ {
    export type Inbound = {
        AgentToken: string;
    };

    export const inboundSchema: z.ZodType<PurchaseCargoSecurity, z.ZodTypeDef, Inbound> = z
        .object({
            AgentToken: z.string(),
        })
        .transform((v) => {
            return {
                agentToken: v.AgentToken,
            };
        });

    export type Outbound = {
        AgentToken: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PurchaseCargoSecurity> = z
        .object({
            agentToken: z.string(),
        })
        .transform((v) => {
            return {
                AgentToken: v.agentToken,
            };
        });
}

/** @internal */
export namespace PurchaseCargoPurchaseCargoRequest$ {
    export type Inbound = {
        symbol: components.TradeSymbolJson;
        units: number;
    };

    export const inboundSchema: z.ZodType<
        PurchaseCargoPurchaseCargoRequest,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            symbol: components.TradeSymbolJson$,
            units: z.number().int(),
        })
        .transform((v) => {
            return {
                symbol: v.symbol,
                units: v.units,
            };
        });

    export type Outbound = {
        symbol: components.TradeSymbolJson;
        units: number;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        PurchaseCargoPurchaseCargoRequest
    > = z
        .object({
            symbol: components.TradeSymbolJson$,
            units: z.number().int(),
        })
        .transform((v) => {
            return {
                symbol: v.symbol,
                units: v.units,
            };
        });
}

/** @internal */
export namespace PurchaseCargoRequest$ {
    export type Inbound = {
        shipSymbol: string;
        RequestBody?: PurchaseCargoPurchaseCargoRequest$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<PurchaseCargoRequest, z.ZodTypeDef, Inbound> = z
        .object({
            shipSymbol: z.string(),
            RequestBody: z.lazy(() => PurchaseCargoPurchaseCargoRequest$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                shipSymbol: v.shipSymbol,
                ...(v.RequestBody === undefined ? null : { requestBody: v.RequestBody }),
            };
        });

    export type Outbound = {
        shipSymbol: string;
        RequestBody?: PurchaseCargoPurchaseCargoRequest$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PurchaseCargoRequest> = z
        .object({
            shipSymbol: z.string(),
            requestBody: z.lazy(() => PurchaseCargoPurchaseCargoRequest$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                shipSymbol: v.shipSymbol,
                ...(v.requestBody === undefined ? null : { RequestBody: v.requestBody }),
            };
        });
}

/** @internal */
export namespace PurchaseCargoData$ {
    export type Inbound = {
        agent: components.AgentJson$.Inbound;
        cargo: components.ShipCargoJson$.Inbound;
        transaction: components.MarketTransactionJson$.Inbound;
    };

    export const inboundSchema: z.ZodType<PurchaseCargoData, z.ZodTypeDef, Inbound> = z
        .object({
            agent: components.AgentJson$.inboundSchema,
            cargo: components.ShipCargoJson$.inboundSchema,
            transaction: components.MarketTransactionJson$.inboundSchema,
        })
        .transform((v) => {
            return {
                agent: v.agent,
                cargo: v.cargo,
                transaction: v.transaction,
            };
        });

    export type Outbound = {
        agent: components.AgentJson$.Outbound;
        cargo: components.ShipCargoJson$.Outbound;
        transaction: components.MarketTransactionJson$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PurchaseCargoData> = z
        .object({
            agent: components.AgentJson$.outboundSchema,
            cargo: components.ShipCargoJson$.outboundSchema,
            transaction: components.MarketTransactionJson$.outboundSchema,
        })
        .transform((v) => {
            return {
                agent: v.agent,
                cargo: v.cargo,
                transaction: v.transaction,
            };
        });
}

/** @internal */
export namespace PurchaseCargoPurchaseCargo201Response$ {
    export type Inbound = {
        data: PurchaseCargoData$.Inbound;
    };

    export const inboundSchema: z.ZodType<
        PurchaseCargoPurchaseCargo201Response,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            data: z.lazy(() => PurchaseCargoData$.inboundSchema),
        })
        .transform((v) => {
            return {
                data: v.data,
            };
        });

    export type Outbound = {
        data: PurchaseCargoData$.Outbound;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        PurchaseCargoPurchaseCargo201Response
    > = z
        .object({
            data: z.lazy(() => PurchaseCargoData$.outboundSchema),
        })
        .transform((v) => {
            return {
                data: v.data,
            };
        });
}

/** @internal */
export namespace PurchaseCargoResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        "Purchase Cargo 201 Response"?: PurchaseCargoPurchaseCargo201Response$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<PurchaseCargoResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            "Purchase Cargo 201 Response": z
                .lazy(() => PurchaseCargoPurchaseCargo201Response$.inboundSchema)
                .optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v["Purchase Cargo 201 Response"] === undefined
                    ? null
                    : { purchaseCargo201Response: v["Purchase Cargo 201 Response"] }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        "Purchase Cargo 201 Response"?: PurchaseCargoPurchaseCargo201Response$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PurchaseCargoResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            purchaseCargo201Response: z
                .lazy(() => PurchaseCargoPurchaseCargo201Response$.outboundSchema)
                .optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.purchaseCargo201Response === undefined
                    ? null
                    : { "Purchase Cargo 201 Response": v.purchaseCargo201Response }),
            };
        });
}
