/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import * as z from "zod";

export type RemoveMountSecurity = {
    agentToken: string;
};

export type RemoveMountRemoveMountRequest = {
    /**
     * The symbol of the mount to remove.
     */
    symbol: string;
};

export type RemoveMountRequest = {
    /**
     * The ship's symbol.
     */
    shipSymbol: string;
    requestBody?: RemoveMountRemoveMountRequest | undefined;
};

export type RemoveMountData = {
    /**
     * Agent details.
     */
    agent: components.AgentJson;
    /**
     * List of installed mounts after the removal of the selected mount.
     */
    mounts: Array<components.ShipMountJson>;
    /**
     * Ship cargo details.
     */
    cargo: components.ShipCargoJson;
    /**
     * Result of a transaction for a ship modification, such as installing a mount or a module.
     */
    transaction: components.ShipModificationTransactionJson;
};

/**
 * Successfully removed the mount.
 */
export type RemoveMountRemoveMount201Response = {
    data: RemoveMountData;
};

export type RemoveMountResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Successfully removed the mount.
     */
    removeMount201Response?: RemoveMountRemoveMount201Response | undefined;
};

/** @internal */
export namespace RemoveMountSecurity$ {
    export type Inbound = {
        AgentToken: string;
    };

    export const inboundSchema: z.ZodType<RemoveMountSecurity, z.ZodTypeDef, Inbound> = z
        .object({
            AgentToken: z.string(),
        })
        .transform((v) => {
            return {
                agentToken: v.AgentToken,
            };
        });

    export type Outbound = {
        AgentToken: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RemoveMountSecurity> = z
        .object({
            agentToken: z.string(),
        })
        .transform((v) => {
            return {
                AgentToken: v.agentToken,
            };
        });
}

/** @internal */
export namespace RemoveMountRemoveMountRequest$ {
    export type Inbound = {
        symbol: string;
    };

    export const inboundSchema: z.ZodType<RemoveMountRemoveMountRequest, z.ZodTypeDef, Inbound> = z
        .object({
            symbol: z.string(),
        })
        .transform((v) => {
            return {
                symbol: v.symbol,
            };
        });

    export type Outbound = {
        symbol: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RemoveMountRemoveMountRequest> =
        z
            .object({
                symbol: z.string(),
            })
            .transform((v) => {
                return {
                    symbol: v.symbol,
                };
            });
}

/** @internal */
export namespace RemoveMountRequest$ {
    export type Inbound = {
        shipSymbol: string;
        RequestBody?: RemoveMountRemoveMountRequest$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<RemoveMountRequest, z.ZodTypeDef, Inbound> = z
        .object({
            shipSymbol: z.string(),
            RequestBody: z.lazy(() => RemoveMountRemoveMountRequest$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                shipSymbol: v.shipSymbol,
                ...(v.RequestBody === undefined ? null : { requestBody: v.RequestBody }),
            };
        });

    export type Outbound = {
        shipSymbol: string;
        RequestBody?: RemoveMountRemoveMountRequest$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RemoveMountRequest> = z
        .object({
            shipSymbol: z.string(),
            requestBody: z.lazy(() => RemoveMountRemoveMountRequest$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                shipSymbol: v.shipSymbol,
                ...(v.requestBody === undefined ? null : { RequestBody: v.requestBody }),
            };
        });
}

/** @internal */
export namespace RemoveMountData$ {
    export type Inbound = {
        agent: components.AgentJson$.Inbound;
        mounts: Array<components.ShipMountJson$.Inbound>;
        cargo: components.ShipCargoJson$.Inbound;
        transaction: components.ShipModificationTransactionJson$.Inbound;
    };

    export const inboundSchema: z.ZodType<RemoveMountData, z.ZodTypeDef, Inbound> = z
        .object({
            agent: components.AgentJson$.inboundSchema,
            mounts: z.array(components.ShipMountJson$.inboundSchema),
            cargo: components.ShipCargoJson$.inboundSchema,
            transaction: components.ShipModificationTransactionJson$.inboundSchema,
        })
        .transform((v) => {
            return {
                agent: v.agent,
                mounts: v.mounts,
                cargo: v.cargo,
                transaction: v.transaction,
            };
        });

    export type Outbound = {
        agent: components.AgentJson$.Outbound;
        mounts: Array<components.ShipMountJson$.Outbound>;
        cargo: components.ShipCargoJson$.Outbound;
        transaction: components.ShipModificationTransactionJson$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RemoveMountData> = z
        .object({
            agent: components.AgentJson$.outboundSchema,
            mounts: z.array(components.ShipMountJson$.outboundSchema),
            cargo: components.ShipCargoJson$.outboundSchema,
            transaction: components.ShipModificationTransactionJson$.outboundSchema,
        })
        .transform((v) => {
            return {
                agent: v.agent,
                mounts: v.mounts,
                cargo: v.cargo,
                transaction: v.transaction,
            };
        });
}

/** @internal */
export namespace RemoveMountRemoveMount201Response$ {
    export type Inbound = {
        data: RemoveMountData$.Inbound;
    };

    export const inboundSchema: z.ZodType<
        RemoveMountRemoveMount201Response,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            data: z.lazy(() => RemoveMountData$.inboundSchema),
        })
        .transform((v) => {
            return {
                data: v.data,
            };
        });

    export type Outbound = {
        data: RemoveMountData$.Outbound;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        RemoveMountRemoveMount201Response
    > = z
        .object({
            data: z.lazy(() => RemoveMountData$.outboundSchema),
        })
        .transform((v) => {
            return {
                data: v.data,
            };
        });
}

/** @internal */
export namespace RemoveMountResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        "Remove Mount 201 Response"?: RemoveMountRemoveMount201Response$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<RemoveMountResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            "Remove Mount 201 Response": z
                .lazy(() => RemoveMountRemoveMount201Response$.inboundSchema)
                .optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v["Remove Mount 201 Response"] === undefined
                    ? null
                    : { removeMount201Response: v["Remove Mount 201 Response"] }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        "Remove Mount 201 Response"?: RemoveMountRemoveMount201Response$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RemoveMountResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            removeMount201Response: z
                .lazy(() => RemoveMountRemoveMount201Response$.outboundSchema)
                .optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.removeMount201Response === undefined
                    ? null
                    : { "Remove Mount 201 Response": v.removeMount201Response }),
            };
        });
}
