/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import * as z from "zod";

export type WarpShipSecurity = {
    agentToken: string;
};

export type WarpShipRequestBody = {
    /**
     * The target destination.
     */
    waypointSymbol: string;
};

export type WarpShipRequest = {
    /**
     * The ship symbol.
     */
    shipSymbol: string;
    requestBody?: WarpShipRequestBody | undefined;
};

export type WarpShipData = {
    /**
     * Details of the ship's fuel tanks including how much fuel was consumed during the last transit or action.
     */
    fuel: components.ShipFuelJson;
    /**
     * The navigation information of the ship.
     */
    nav: components.ShipNavJson;
};

/**
 * The successful transit information including the route details and changes to ship fuel. The route includes the expected time of arrival.
 */
export type WarpShipResponseBody = {
    data: WarpShipData;
};

export type WarpShipResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * The successful transit information including the route details and changes to ship fuel. The route includes the expected time of arrival.
     */
    object?: WarpShipResponseBody | undefined;
};

/** @internal */
export namespace WarpShipSecurity$ {
    export type Inbound = {
        AgentToken: string;
    };

    export const inboundSchema: z.ZodType<WarpShipSecurity, z.ZodTypeDef, Inbound> = z
        .object({
            AgentToken: z.string(),
        })
        .transform((v) => {
            return {
                agentToken: v.AgentToken,
            };
        });

    export type Outbound = {
        AgentToken: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WarpShipSecurity> = z
        .object({
            agentToken: z.string(),
        })
        .transform((v) => {
            return {
                AgentToken: v.agentToken,
            };
        });
}

/** @internal */
export namespace WarpShipRequestBody$ {
    export type Inbound = {
        waypointSymbol: string;
    };

    export const inboundSchema: z.ZodType<WarpShipRequestBody, z.ZodTypeDef, Inbound> = z
        .object({
            waypointSymbol: z.string(),
        })
        .transform((v) => {
            return {
                waypointSymbol: v.waypointSymbol,
            };
        });

    export type Outbound = {
        waypointSymbol: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WarpShipRequestBody> = z
        .object({
            waypointSymbol: z.string(),
        })
        .transform((v) => {
            return {
                waypointSymbol: v.waypointSymbol,
            };
        });
}

/** @internal */
export namespace WarpShipRequest$ {
    export type Inbound = {
        shipSymbol: string;
        RequestBody?: WarpShipRequestBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<WarpShipRequest, z.ZodTypeDef, Inbound> = z
        .object({
            shipSymbol: z.string(),
            RequestBody: z.lazy(() => WarpShipRequestBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                shipSymbol: v.shipSymbol,
                ...(v.RequestBody === undefined ? null : { requestBody: v.RequestBody }),
            };
        });

    export type Outbound = {
        shipSymbol: string;
        RequestBody?: WarpShipRequestBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WarpShipRequest> = z
        .object({
            shipSymbol: z.string(),
            requestBody: z.lazy(() => WarpShipRequestBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                shipSymbol: v.shipSymbol,
                ...(v.requestBody === undefined ? null : { RequestBody: v.requestBody }),
            };
        });
}

/** @internal */
export namespace WarpShipData$ {
    export type Inbound = {
        fuel: components.ShipFuelJson$.Inbound;
        nav: components.ShipNavJson$.Inbound;
    };

    export const inboundSchema: z.ZodType<WarpShipData, z.ZodTypeDef, Inbound> = z
        .object({
            fuel: components.ShipFuelJson$.inboundSchema,
            nav: components.ShipNavJson$.inboundSchema,
        })
        .transform((v) => {
            return {
                fuel: v.fuel,
                nav: v.nav,
            };
        });

    export type Outbound = {
        fuel: components.ShipFuelJson$.Outbound;
        nav: components.ShipNavJson$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WarpShipData> = z
        .object({
            fuel: components.ShipFuelJson$.outboundSchema,
            nav: components.ShipNavJson$.outboundSchema,
        })
        .transform((v) => {
            return {
                fuel: v.fuel,
                nav: v.nav,
            };
        });
}

/** @internal */
export namespace WarpShipResponseBody$ {
    export type Inbound = {
        data: WarpShipData$.Inbound;
    };

    export const inboundSchema: z.ZodType<WarpShipResponseBody, z.ZodTypeDef, Inbound> = z
        .object({
            data: z.lazy(() => WarpShipData$.inboundSchema),
        })
        .transform((v) => {
            return {
                data: v.data,
            };
        });

    export type Outbound = {
        data: WarpShipData$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WarpShipResponseBody> = z
        .object({
            data: z.lazy(() => WarpShipData$.outboundSchema),
        })
        .transform((v) => {
            return {
                data: v.data,
            };
        });
}

/** @internal */
export namespace WarpShipResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        object?: WarpShipResponseBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<WarpShipResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            object: z.lazy(() => WarpShipResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        object?: WarpShipResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WarpShipResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            object: z.lazy(() => WarpShipResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
