/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The symbol of the faction.
 */
export enum FactionSymbolJson {
    Cosmic = "COSMIC",
    Void = "VOID",
    Galactic = "GALACTIC",
    Quantum = "QUANTUM",
    Dominion = "DOMINION",
    Astro = "ASTRO",
    Corsairs = "CORSAIRS",
    Obsidian = "OBSIDIAN",
    Aegis = "AEGIS",
    United = "UNITED",
    Solitary = "SOLITARY",
    Cobalt = "COBALT",
    Omega = "OMEGA",
    Echo = "ECHO",
    Lords = "LORDS",
    Cult = "CULT",
    Ancients = "ANCIENTS",
    Shadow = "SHADOW",
    Ethereal = "ETHEREAL",
}

/** @internal */
export const FactionSymbolJson$ = z.nativeEnum(FactionSymbolJson);
