/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The ship's set speed when traveling between waypoints or systems.
 */
export enum ShipNavFlightModeJson {
    Drift = "DRIFT",
    Stealth = "STEALTH",
    Cruise = "CRUISE",
    Burn = "BURN",
}

/** @internal */
export const ShipNavFlightModeJson$ = z.nativeEnum(ShipNavFlightModeJson);
