/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { TradeSymbolJsonTradeSymbolJson, TradeSymbolJsonTradeSymbolJson$ } from "./factionjson";
import * as z from "zod";

/**
 * A yield from the siphon operation.
 */
export type SiphonYieldJson = {
    /**
     * The good's symbol.
     */
    symbol: TradeSymbolJsonTradeSymbolJson;
    /**
     * The number of units siphoned that were placed into the ship's cargo hold.
     */
    units: number;
};

/**
 * Siphon details.
 */
export type SiphonJson = {
    /**
     * Symbol of the ship that executed the siphon.
     */
    shipSymbol: string;
    /**
     * A yield from the siphon operation.
     */
    yield: SiphonYieldJson;
};

/** @internal */
export namespace SiphonYieldJson$ {
    export type Inbound = {
        symbol: TradeSymbolJsonTradeSymbolJson;
        units: number;
    };

    export const inboundSchema: z.ZodType<SiphonYieldJson, z.ZodTypeDef, Inbound> = z
        .object({
            symbol: TradeSymbolJsonTradeSymbolJson$,
            units: z.number().int(),
        })
        .transform((v) => {
            return {
                symbol: v.symbol,
                units: v.units,
            };
        });

    export type Outbound = {
        symbol: TradeSymbolJsonTradeSymbolJson;
        units: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, SiphonYieldJson> = z
        .object({
            symbol: TradeSymbolJsonTradeSymbolJson$,
            units: z.number().int(),
        })
        .transform((v) => {
            return {
                symbol: v.symbol,
                units: v.units,
            };
        });
}

/** @internal */
export namespace SiphonJson$ {
    export type Inbound = {
        shipSymbol: string;
        yield: SiphonYieldJson$.Inbound;
    };

    export const inboundSchema: z.ZodType<SiphonJson, z.ZodTypeDef, Inbound> = z
        .object({
            shipSymbol: z.string(),
            yield: z.lazy(() => SiphonYieldJson$.inboundSchema),
        })
        .transform((v) => {
            return {
                shipSymbol: v.shipSymbol,
                yield: v.yield,
            };
        });

    export type Outbound = {
        shipSymbol: string;
        yield: SiphonYieldJson$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, SiphonJson> = z
        .object({
            shipSymbol: z.string(),
            yield: z.lazy(() => SiphonYieldJson$.outboundSchema),
        })
        .transform((v) => {
            return {
                shipSymbol: v.shipSymbol,
                yield: v.yield,
            };
        });
}
