/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * A surveyed deposit of a mineral or resource available for extraction.
 */
export type SurveyDepositJson = {
    /**
     * The symbol of the deposit.
     */
    symbol: string;
};

/**
 * The size of the deposit. This value indicates how much can be extracted from the survey before it is exhausted.
 */
export enum Size {
    Small = "SMALL",
    Moderate = "MODERATE",
    Large = "LARGE",
}

/**
 * A resource survey of a waypoint, detailing a specific extraction location and the types of resources that can be found there.
 */
export type SurveyJson = {
    /**
     * A unique signature for the location of this survey. This signature is verified when attempting an extraction using this survey.
     */
    signature: string;
    /**
     * The symbol of the waypoint that this survey is for.
     */
    symbol: string;
    /**
     * A list of deposits that can be found at this location. A ship will extract one of these deposits when using this survey in an extraction request. If multiple deposits of the same type are present, the chance of extracting that deposit is increased.
     */
    deposits: Array<SurveyDepositJson>;
    /**
     * The date and time when the survey expires. After this date and time, the survey will no longer be available for extraction.
     */
    expiration: Date;
    /**
     * The size of the deposit. This value indicates how much can be extracted from the survey before it is exhausted.
     */
    size: Size;
};

/** @internal */
export namespace SurveyDepositJson$ {
    export type Inbound = {
        symbol: string;
    };

    export const inboundSchema: z.ZodType<SurveyDepositJson, z.ZodTypeDef, Inbound> = z
        .object({
            symbol: z.string(),
        })
        .transform((v) => {
            return {
                symbol: v.symbol,
            };
        });

    export type Outbound = {
        symbol: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, SurveyDepositJson> = z
        .object({
            symbol: z.string(),
        })
        .transform((v) => {
            return {
                symbol: v.symbol,
            };
        });
}

/** @internal */
export const Size$ = z.nativeEnum(Size);

/** @internal */
export namespace SurveyJson$ {
    export type Inbound = {
        signature: string;
        symbol: string;
        deposits: Array<SurveyDepositJson$.Inbound>;
        expiration: string;
        size: Size;
    };

    export const inboundSchema: z.ZodType<SurveyJson, z.ZodTypeDef, Inbound> = z
        .object({
            signature: z.string(),
            symbol: z.string(),
            deposits: z.array(z.lazy(() => SurveyDepositJson$.inboundSchema)),
            expiration: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v)),
            size: Size$,
        })
        .transform((v) => {
            return {
                signature: v.signature,
                symbol: v.symbol,
                deposits: v.deposits,
                expiration: v.expiration,
                size: v.size,
            };
        });

    export type Outbound = {
        signature: string;
        symbol: string;
        deposits: Array<SurveyDepositJson$.Outbound>;
        expiration: string;
        size: Size;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, SurveyJson> = z
        .object({
            signature: z.string(),
            symbol: z.string(),
            deposits: z.array(z.lazy(() => SurveyDepositJson$.outboundSchema)),
            expiration: z.date().transform((v) => v.toISOString()),
            size: Size$,
        })
        .transform((v) => {
            return {
                signature: v.signature,
                symbol: v.symbol,
                deposits: v.deposits,
                expiration: v.expiration,
                size: v.size,
            };
        });
}
