/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The type of waypoint.
 */
export enum WaypointTypeJson {
    Planet = "PLANET",
    GasGiant = "GAS_GIANT",
    Moon = "MOON",
    OrbitalStation = "ORBITAL_STATION",
    JumpGate = "JUMP_GATE",
    AsteroidField = "ASTEROID_FIELD",
    Asteroid = "ASTEROID",
    EngineeredAsteroid = "ENGINEERED_ASTEROID",
    AsteroidBase = "ASTEROID_BASE",
    Nebula = "NEBULA",
    DebrisField = "DEBRIS_FIELD",
    GravityWell = "GRAVITY_WELL",
    ArtificialGravityWell = "ARTIFICIAL_GRAVITY_WELL",
    FuelStation = "FUEL_STATION",
}

/** @internal */
export const WaypointTypeJson$ = z.nativeEnum(WaypointTypeJson);
